### ISSUE TITLE
Some questions about using the official postprocessing shader

### ISSUE THREAD

**Issue by FlowSand** [haxiomic/haxe-shader-demo#1]
Hello, recently I need to use the threejs post-processing library in my haxe project. After setting it with dts2hx tool and writing it according to the official case code, I got a error render result（a whole red texture）, and the stack information is as follows:
![1](https://user-images.githubusercontent.com/16620079/204126694-30a8c2c1-3639-425f-9d58-b61b63a4a3e2.png)
It looks like its frag and vert function was the default value, Is there something wrong with my usage? Or I need to write the glsl code in the code according to the CustomShader of this reposity

**Comment by haxiomic** [comment]
Interesting, did you get any GLSL error? What does the error log show?

**Comment by FlowSand** [comment]
Well，I found the problem:sweat_smile:! I should write like this: XXShader.XXShader
![image](https://user-images.githubusercontent.com/16620079/204142759-41423993-eb48-465c-94a8-8c2d48413b5e.png)
![image](https://user-images.githubusercontent.com/16620079/204142784-dff654ae-feea-48db-a30a-9310b34b3df7.png)

**Comment by haxiomic** [comment]
oh interesting, I think this will go away eventually in the next pass through dts2hx now haxe supports module level fields

Glad it works!
